'use strict'

export const SERVER_FAILED = 'SERVER_FAILED'
export const API_FAILED = 'API_FAILED'

export const APP_INFO_LOADED = 'APP_INFO_LOADED'
export const PLATFORM_CHANGED = 'PLATFORM_CHANGED'
export const PACK_CHANGED = 'PACK_CHANGED'
export const SEO_PACK_CHANGED = 'SEO_PACK_CHANGED'
export const SEARCH_COLOR_CHANGED = 'SEARCH_COLOR_CHANGED'
export const SEARCH_SHAPE_CHANGED = 'SEARCH_SHAPE_CHANGED'
export const SEARCH_FORMAT_CHANGED = 'SEARCH_FORMAT_CHANGED'

// around app ui
export const ICONS_GRID_STYLE_CHANGED = 'ICONS_GRID_STYLE_CHANGED'
export const EXTENDED_ICONS_GRID_STYLE_CHANGED = 'EXTENDED_ICONS_GRID_STYLE_CHANGED'
export const MODE_CHANGED_TO_ICON = 'MODE_CHANGED_TO_ICON'
export const MODE_CHANGED_TO_COLLECTIONS = 'MODE_CHANGED_TO_COLLECTIONS'

export const EFFECTS_SHOWN = 'EFFECTS_SHOWN'
export const EFFECTS_HIDDEN = 'EFFECTS_HIDDEN'

export const CORNER_AD_SHOWN = 'CORNER_AD_SHOWN'
export const CORNER_AD_HIDDEN = 'CORNER_AD_HIDDEN'

export const ICONS_EXPANDED = 'ICONS_EXPANDED'
export const ICONS_SHRINKED = 'ICONS_SHRINKED'

// around sidebars
export const LEFT_SIDEBAR_ENABLED = 'LEFT_SIDEBAR_ENABLED'
export const LEFT_SIDEBAR_DISABLED = 'LEFT_SIDEBAR_DISABLED'
export const LEFT_SIDEBAR_SHOWN = 'LEFT_SIDEBAR_SHOWN'
export const LEFT_SIDEBAR_HIDDEN = 'LEFT_SIDEBAR_HIDDEN'

export const RIGHT_SIDEBAR_ENABLED = 'RIGHT_SIDEBAR_ENABLED'
export const RIGHT_SIDEBAR_DISABLED = 'RIGHT_SIDEBAR_DISABLED'
export const RIGHT_SIDEBAR_SHOWN = 'RIGHT_SIDEBAR_SHOWN'
export const RIGHT_SIDEBAR_HIDDEN = 'RIGHT_SIDEBAR_HIDDEN'

// mobile search
export const MOBILE_SEARCH_SHOWN = 'MOBILE_SEARCH_SHOWN'
export const MOBILE_SEARCH_HIDDEN = 'MOBILE_SEARCH_HIDDEN'

// select changed on mobile
export const SELECT_PLATFORM_CHANGED = 'SELECT_PLATFORM_CHANGED'
export const SELECT_PLATFORM_RESET = 'SELECT_PLATFORM_RESET'
